#cloud-config
disable_root: true

users:
  - default
  - name: ubuntu
    groups: sudo
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh-authorized-keys:
      - ssh-rsa {{ auth_key }}
      - ssh-rsa {{ ssh_pub_key }}

package_update: true
packages:
  - git
  - ruby-full
  - ruby-bundler
  - apt-transport-https
  - ca-certificates
  - build-essential
  - mongodb-org

bootcmd:
  - wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | sudo apt-key add -
  - echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-4.2.list
  - apt-get ubuntu

runcmd:
  - systemctl start mongod
  - systemctl enable mongod
  - cd ~
  - git clone -b monolith https://github.com/express42/reddit.git
  - cd reddit && bundle install
  - puma -d
